language: ruby
before_install: gem install bundler
install: bundle install --jobs=3 --retry=3
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - gemfile/mime_types_1.gemfile
  - gemfile/mime_types_2.gemfile
  - gemfile/mime_types_3.gemfile
